name: Automatically deploy to nest

on: [push]

jobs:
  
  deploy-to-nest:
      runs-on: ubuntu-latest
      steps:
      - name: Connect to ssh, pull and systemctl restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hackclub.app
          username: ponderslime
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/ponderslime/pub/samwise-smallburrow
            git pull
            systemctl --user restart SamwiseSmallburrow.service 
