name: Automatically deploy to nest

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: SamwiseSmallburrow
    steps:
      - name: Connect to ssh, pull and systemctl restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ponderslime
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/ponderslime/pub/samwise-smallburrow
            git pull
            systemctl --user restart SamwiseSmallburrow.service
            ssh -O exit ponderslime@hackclub.app
