name: Automatically deploy to nest

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: SamwiseSmallburrow
    steps:
      - name: Connect to ssh, pull and systemctl restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hackclub.app
          username: ponderslime
          key: ${{ secrets.SAMWISEKEY }}
          port: 22
          script: |
            cd /home/ponderslime/pub/samwise-smallburrow
            git pull
            systemctl --user restart SamwiseSmallburrow.service 
